### ISSUE TITLE
void Function(String, String)' can't be assigned to the parameter type 'void Function(String, String?)?' because 'String?' is nullable and 'String' isn't. onAnnouncementChangedFromGroup: onAnnouncementChangedFromGroup,

### ISSUE THREAD

**Issue by BambangHeriSetiawan** [AgoraIO-Usecase/AgoraChat-UIKit-flutter#15]
agora_chat_uikit-2.0.0/lib/sdk_service/wrappers/group_wrapper.dart:18:41: Error: The argument type 'void Function(String, String)' can't be assigned to the parameter type 'void Function(String, String?)?' because 'String?' is nullable and 'String' isn't. onAnnouncementChangedFromGroup: onAnnouncementChangedFromGroup

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.3, on macOS 12.7.6 21H1320 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.100.2)
```

```
video_player: 2.9.3
  file_picker: ^10.1.2
  record: ^6.0.0
  audioplayers: ^5.2.0
  agora_chat_sdk: ^1.3.2
  agora_chat_uikit: ^2.0.0

  # google_mobile_ads: ^6.0.0
  # flutter_osm_plugin: ^1.3.7
  # rate_my_app: ^2.2.0
  
dependency_overrides:
  intl: ^0.20.2
  video_player: 2.9.3
  file_picker: ^10.1.2
  record: ^6.0.0
  flutter_localization: ^0.3.2
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  audioplayers: ^5.2.0
  path_provider: ^2.0.15
  agora_chat_sdk: ^1.3.2
```
